use std::collections::BTreeSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use proc_macro2::Span;
use syn::visit::{self, Visit};
use syn::{Attribute, ItemFn, ItemMod};
use walkdir::{DirEntry, WalkDir};

use crate::finding::{AnalysisReport, Claim, ClaimKind, Evidence, Finding, Location};

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct ExplicitTest {
    pub name: String,
    pub path: PathBuf,
    pub line: usize,
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FilteredLibTestCommand {
    pub workflow_path: PathBuf,
    pub line: usize,
    pub command: String,
    pub filter: String,
}

#[derive(Debug, Default)]
pub struct CiTestFilterReport {
    pub tests: Vec<ExplicitTest>,
    pub possible_name_fragments: BTreeSet<String>,
    pub commands: Vec<FilteredLibTestCommand>,
    pub parse_failures: Vec<(PathBuf, String)>,
}

pub fn analyze_ci_test_filters(root: &Path) -> Result<CiTestFilterReport, Box<dyn Error>> {
    let mut report = CiTestFilterReport::default();
    collect_explicit_tests(root, &mut report)?;
    collect_workflow_commands(root, &mut report)?;

    report
        .tests
        .sort_by(|a, b| a.path.cmp(&b.path).then(a.line.cmp(&b.line)));
    report.commands.sort_by(|a, b| {
        a.workflow_path
            .cmp(&b.workflow_path)
            .then(a.line.cmp(&b.line))
    });
    report.parse_failures.sort_by(|a, b| a.0.cmp(&b.0));

    Ok(report)
}

pub fn build_ci_test_filter_analysis(root: &Path, report: &CiTestFilterReport) -> AnalysisReport {
    let mut analysis = AnalysisReport::new(
        "ci-test-filter-inventory",
        root.to_string_lossy().into_owned(),
    );

    analysis.claims.push(Claim::new(
        ClaimKind::Proven,
        format!(
            "The syntax scan found {} explicit `#[test]` function declaration(s) and {} supported filtered `cargo test --lib` workflow command(s).",
            report.tests.len(),
            report.commands.len()
        ),
    ));

    if !report.parse_failures.is_empty() {
        let mut claim = Claim::new(
            ClaimKind::Unknown,
            format!(
                "{} Rust file(s) failed to parse, so the explicit test inventory is incomplete.",
                report.parse_failures.len()
            ),
        );
        for (path, error) in report.parse_failures.iter().take(5) {
            claim = claim.with_evidence(Evidence::at(
                error.clone(),
                Location::new(relative_path(root, path), None),
            ));
        }
        analysis.claims.push(claim);
        return analysis;
    }

    if report.tests.is_empty() {
        analysis.claims.push(Claim::new(
            ClaimKind::Unknown,
            "No explicit `#[test]` declarations were found, so this experiment has no useful declared-test inventory to compare.",
        ));
        return analysis;
    }

    for command in &report.commands {
        if has_possible_explicit_match(report, &command.filter) {
            continue;
        }

        let workflow_location = Location::new(
            relative_path(root, &command.workflow_path),
            Some(command.line),
        );

        let proven = Claim::new(
            ClaimKind::Proven,
            format!(
                "The workflow contains the supported literal command `{}` with test filter `{}`.",
                command.command, command.filter
            ),
        )
        .with_evidence(Evidence::at(
            "Recognized `cargo test --lib FILTER` command.",
            workflow_location.clone(),
        ));

        let mut observed = Claim::new(
            ClaimKind::Observed,
            format!(
                "None of the {} explicit `#[test]` function names, inline module names, or Rust source path components found by this syntax scan contains `{}`.",
                report.tests.len(),
                command.filter
            ),
        );
        for test in report.tests.iter().take(5) {
            observed = observed.with_evidence(Evidence::at(
                format!("Explicit test `{}`.", test.name),
                Location::new(relative_path(root, &test.path), Some(test.line)),
            ));
        }

        let unknown = Claim::new(
            ClaimKind::Unknown,
            "This syntax-only inventory does not enumerate tests generated by macros or other build-time mechanisms. The command should be executed with test listing when zero-selection must be proven.",
        );

        analysis.findings.push(
            Finding::new(
                "ci-test-filter-inventory-miss",
                "CI test filter has no explicit test-name match",
            )
            .at(workflow_location)
            .with_claim(proven)
            .with_claim(observed)
            .with_claim(unknown)
            .with_question(format!(
                "Is this workflow step still selecting the intended library test for `{}`?",
                command.filter
            )),
        );
    }

    analysis
}

pub fn print_ci_test_filter_report(root: &Path, report: &CiTestFilterReport) {
    println!("CI TEST FILTER INVENTORY");
    println!("  explicit #[test] declarations   {}", report.tests.len());
    println!(
        "  supported filtered commands     {}",
        report.commands.len()
    );

    if !report.parse_failures.is_empty() {
        println!("\nPARSE NOTES");
        for (path, error) in &report.parse_failures {
            println!("  {}: {error}", relative_path(root, path));
        }
        println!("\nOBSERVATION");
        println!("  The explicit test inventory is incomplete, so filter misses are suppressed.");
        return;
    }

    let mut misses = 0;
    for command in &report.commands {
        let direct_matches = report
            .tests
            .iter()
            .filter(|test| test.name.contains(&command.filter))
            .count();
        let qualifier_match = report
            .possible_name_fragments
            .iter()
            .any(|fragment| fragment.contains(&command.filter));
        let path = relative_path(root, &command.workflow_path);
        println!(
            "\n  {}:{}  filter `{}` -> {} explicit function-name match(es)",
            path, command.line, command.filter, direct_matches
        );

        if direct_matches == 0 && qualifier_match {
            println!("    possible module/path qualifier match; syntax-only miss suppressed");
        } else if direct_matches == 0 && !report.tests.is_empty() {
            misses += 1;
            println!("    command: {}", command.command);
        }
    }

    if report.commands.is_empty() {
        println!("\nOBSERVATION");
        println!("  No supported `cargo test --lib FILTER` workflow commands were found.");
    } else if misses == 0 {
        println!("\nOBSERVATION");
        println!(
            "  Every supported workflow filter has an explicit function-name or module/path hint."
        );
    } else {
        println!("\nQUESTION");
        println!(
            "  Do the zero-hint filters rely on generated tests, or have their intended tests moved or been renamed?"
        );
    }
}

fn has_possible_explicit_match(report: &CiTestFilterReport, filter: &str) -> bool {
    report.tests.iter().any(|test| test.name.contains(filter))
        || report
            .possible_name_fragments
            .iter()
            .any(|fragment| fragment.contains(filter))
}

fn collect_explicit_tests(
    root: &Path,
    report: &mut CiTestFilterReport,
) -> Result<(), Box<dyn Error>> {
    for entry in WalkDir::new(root)
        .into_iter()
        .filter_entry(should_visit_rust)
    {
        let entry = entry?;
        if !entry.file_type().is_file()
            || entry.path().extension().and_then(|ext| ext.to_str()) != Some("rs")
        {
            continue;
        }

        let path = entry.path();
        collect_path_fragments(root, path, &mut report.possible_name_fragments);

        let source = fs::read_to_string(path)?;
        match syn::parse_file(&source) {
            Ok(file) => {
                let mut visitor = ExplicitTestVisitor {
                    path,
                    tests: &mut report.tests,
                    possible_name_fragments: &mut report.possible_name_fragments,
                };
                visitor.visit_file(&file);
            }
            Err(error) => report
                .parse_failures
                .push((path.to_path_buf(), error.to_string())),
        }
    }

    Ok(())
}

fn collect_path_fragments(root: &Path, path: &Path, fragments: &mut BTreeSet<String>) {
    let relative = path.strip_prefix(root).unwrap_or(path);
    for component in relative.components() {
        let value = component.as_os_str().to_string_lossy();
        let value = value.strip_suffix(".rs").unwrap_or(&value);
        if !value.is_empty() {
            fragments.insert(value.to_string());
        }
    }
}

fn collect_workflow_commands(
    root: &Path,
    report: &mut CiTestFilterReport,
) -> Result<(), Box<dyn Error>> {
    let workflows = root.join(".github/workflows");
    if !workflows.is_dir() {
        return Ok(());
    }

    for entry in WalkDir::new(&workflows).max_depth(1) {
        let entry = entry?;
        if !entry.file_type().is_file() || !is_yaml(entry.path()) {
            continue;
        }

        let source = fs::read_to_string(entry.path())?;
        for (index, line) in source.lines().enumerate() {
            let Some(command) = workflow_shell_line(line) else {
                continue;
            };
            let Some(filter) = parse_filtered_lib_test_command(command) else {
                continue;
            };
            report.commands.push(FilteredLibTestCommand {
                workflow_path: entry.path().to_path_buf(),
                line: index + 1,
                command: command.to_string(),
                filter,
            });
        }
    }

    Ok(())
}

fn workflow_shell_line(line: &str) -> Option<&str> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.ends_with('\\') {
        return None;
    }

    let step = trimmed
        .strip_prefix("- ")
        .map(str::trim)
        .unwrap_or(trimmed);
    let candidate = step.strip_prefix("run:").map(str::trim).unwrap_or(step);
    if candidate.starts_with("cargo test ") {
        Some(candidate)
    } else {
        None
    }
}

fn parse_filtered_lib_test_command(command: &str) -> Option<String> {
    let tokens: Vec<_> = command.split_whitespace().collect();
    if tokens.len() < 4 || tokens[0] != "cargo" || tokens[1] != "test" {
        return None;
    }

    let mut saw_lib = false;
    let mut filter = None;
    let mut index = 2;

    while index < tokens.len() {
        let token = tokens[index];
        if token == "--" {
            break;
        }

        match token {
            "--lib" => saw_lib = true,
            "--locked"
            | "--quiet"
            | "-q"
            | "--release"
            | "--no-fail-fast"
            | "--no-default-features"
            | "--all-features"
            | "--frozen"
            | "--offline" => {}
            "--features" | "--color" | "--jobs" | "-j" | "--profile" | "--target"
            | "--target-dir" | "--config" => {
                index += 1;
                if index >= tokens.len() {
                    return None;
                }
            }
            "-p" | "--package" | "--workspace" | "--test" | "--tests" | "--bin" | "--bins"
            | "--example" | "--examples" | "--doc" | "--all-targets" | "--exclude"
            | "--manifest-path" => return None,
            _ if token.starts_with('-') => return None,
            _ => {
                if filter.is_some() {
                    return None;
                }
                let candidate = token.trim_matches(['\'', '"']);
                if !is_simple_test_filter(candidate) {
                    return None;
                }
                filter = Some(candidate.to_string());
            }
        }

        index += 1;
    }

    saw_lib.then_some(filter?).filter(|value| !value.is_empty())
}

fn is_simple_test_filter(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
}

fn is_yaml(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|ext| ext.to_str()),
        Some("yml" | "yaml")
    )
}

fn should_visit_rust(entry: &DirEntry) -> bool {
    if !entry.file_type().is_dir() {
        return true;
    }

    !matches!(
        entry.file_name().to_str(),
        Some(".git" | "target" | "node_modules" | ".venv" | "vendor")
    )
}

struct ExplicitTestVisitor<'a> {
    path: &'a Path,
    tests: &'a mut Vec<ExplicitTest>,
    possible_name_fragments: &'a mut BTreeSet<String>,
}

impl<'ast> Visit<'ast> for ExplicitTestVisitor<'_> {
    fn visit_item_fn(&mut self, node: &'ast ItemFn) {
        if has_test_attr(&node.attrs) {
            let name = node.sig.ident.to_string();
            self.possible_name_fragments.insert(name.clone());
            self.tests.push(ExplicitTest {
                name,
                path: self.path.to_path_buf(),
                line: span_line(node.sig.ident.span()),
            });
        }
        visit::visit_item_fn(self, node);
    }

    fn visit_item_mod(&mut self, node: &'ast ItemMod) {
        self.possible_name_fragments.insert(node.ident.to_string());
        visit::visit_item_mod(self, node);
    }
}

fn has_test_attr(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| attr.path().is_ident("test"))
}

fn span_line(span: Span) -> usize {
    span.start().line
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognizes_narrow_filtered_lib_commands() {
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --locked --lib test_rollback"),
            Some("test_rollback".to_string())
        );
        assert_eq!(
            parse_filtered_lib_test_command(
                "cargo test --features io_uring --lib test_rollback -- --nocapture"
            ),
            Some("test_rollback".to_string())
        );
    }

    #[test]
    fn skips_commands_with_ambiguous_target_selection() {
        assert_eq!(
            parse_filtered_lib_test_command("cargo test -p block --lib test_rollback"),
            None
        );
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --test integration test_rollback"),
            None
        );
    }

    #[test]
    fn skips_complex_shell_and_filter_forms() {
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --lib foo::test_rollback"),
            None
        );
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --lib test_rollback && echo ok"),
            None
        );
    }

    #[test]
    fn extracts_inline_and_block_workflow_commands() {
        assert_eq!(
            workflow_shell_line("      run: cargo test --lib test_rollback"),
            Some("cargo test --lib test_rollback")
        );
        assert_eq!(
            workflow_shell_line("      - run: cargo test --lib test_rollback"),
            Some("cargo test --lib test_rollback")
        );
        assert_eq!(
            workflow_shell_line("          cargo test --lib test_rollback"),
            Some("cargo test --lib test_rollback")
        );
        assert_eq!(workflow_shell_line("        run: |"), None);
    }

    #[test]
    fn module_or_path_fragments_suppress_false_zero_match() {
        let mut report = CiTestFilterReport::default();
        report.tests.push(ExplicitTest {
            name: "works".to_string(),
            path: PathBuf::from("src/foo.rs"),
            line: 1,
        });
        report.possible_name_fragments.insert("foo".to_string());

        assert!(has_possible_explicit_match(&report, "foo"));
        assert!(has_possible_explicit_match(&report, "works"));
        assert!(!has_possible_explicit_match(&report, "missing"));
    }
}
